config/routes.rb
Rails.application.routes.draw do
  root 'races#index'

  resources :races, only: [:index, :show, :create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lap.rb
# frozen_string_literal: true

class Lap < ApplicationRecord
  validates_presence_of :lap_number
end

app/models/lap_racer.rb
# frozen_string_literal: true

class LapRacer < ApplicationRecord
  belongs_to :racer
  belongs_to :lap

  validates_presence_of :lap_duration
  validates_presence_of :lap_time
  validates_presence_of :lap_speed
end

app/models/race.rb
# frozen_string_literal: true

class Race < ApplicationRecord
  validates_presence_of :name
end

app/models/race_info.rb
# frozen_string_literal: true

class RaceInfo < ApplicationRecord
  validates_presence_of :best_lap
  validates_presence_of :time_best_lap
  validates_presence_of :number_laps
  validates_presence_of :total_time
  validates_presence_of :avg_speed

  belongs_to :racer
end

app/models/racer.rb
# frozen_string_literal: true

class Racer < ApplicationRecord
  has_many :lap_racers
  has_many :laps, through: :lap_racers

  validates_presence_of :name
  validates_presence_of :code
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/races_controller.rb
# frozen_string_literal: true

require 'csv'

class RacesController < ApplicationController
  def index
    @races = Race.all
  end

  def create
    @race = Race.new(race_params)

    ActiveRecord::Base.transaction do
      CsvFile.import(params[:file])
      @race.save!
    end

    redirect_to @race
  end

  def show
    @race = Race.find(params[:id])
    @race_infos = RaceInfo.order(:total_time)
    @best_lap = RaceInfo.order(:time_best_lap).first.time_best_lap
  end

  private

  def race_params
    params.require(:race).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GympassKartRacing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/races/index.html.erb
<%= flash[:notice] %>
<h4> Nome da Corrida:</h4>
<%= form_tag races_path, multipart: true do %>
  <%= text_field(:race, :name, :required => true) %>
  <br> <br> <br>
  <h4> Upload csv:</h4>
  <%= file_field_tag :file %>
  <%= submit_tag "Criar" %>
<% end %>

app/views/races/show.html.erb
<h2>Corrida - <%= @race.name %></h2>

<br> <br>

<table>
  <thead>
    <th>Posição chegada</th>
    <th>Código Piloto</th>
    <th>Nome Piloto</th>
    <th>Qtde Voltas Completadas</th>
    <th>Tempo Total de Prova</th>
    <th>Tempo melhor Volta</th>
    <th>Velocidade Média</th>
  </thead>
  <tbody>
    <% @race_infos.each.with_index(1) do |info, index| %>
      <tr>
        <th><%= index %></th>
        <td><%= info.racer.code %></td>
        <td><%= info.racer.name %></td>
        <td><%= info.number_laps %></td>
        <td><%= Time.at(info.total_time).utc.strftime("%H:%M:%S.%L") %></td>
        <td><%= Time.at(info.time_best_lap).utc.strftime("%H:%M:%S.%L") %></td>
            <td><%= info.avg_speed %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br> <br> <br>

<h3> Melhor volta da corrida </h3> <%= raw Time.at(@best_lap).utc.strftime("%H:%M:%S.%L") %>